# Packer Template for GoldenImager-Orchestrator [REFINED]
# Optimized for Hyper-V G2 with Dynamic Variables

variable "iso_url" {
  type    = string
}

variable "vm_name" {
  type    = string
  default = "GoldenImager-Orchestrator-Build"
}

variable "switch_name" {
  type    = string
  default = "Default Switch"
}

variable "admin_password" {
  type    = string
  default = "PackerTemp123!"
}

source "hyperv-iso" "windows" {
  iso_url               = var.iso_url
  iso_checksum          = "none" 
  communicator          = "winrm"
  winrm_username        = "Administrator"
  winrm_password        = var.admin_password
  winrm_timeout         = "4h"
  
  # Payload ISO (Dynamically generated by the GUI)
  cd_files = [
    "../payload/autounattend.xml",
    "../payload/scripts/*"
  ]
  
  generation            = 2
  switch_name           = var.switch_name
  memory                = 4096
  cpus                  = 4
  disk_size             = 81920
  vm_name               = var.vm_name
  
  enable_secure_boot    = true
  secure_boot_template  = "MicrosoftWindows"
  enable_tpm            = true
}

build {
  sources = ["source.hyperv-iso.windows"]

  provisioner "powershell" {
    inline = [
      "Write-Host '[*] Build Phase Complete. Initializing Generalization...'",
      "& $env:SystemRoot\\System32\\Sysprep\\Sysprep.exe /generalize /oobe /quit /quiet"
    ]
  }
}
